[project]
name = "Auto TV"
version = "0.1.0"
dependencies = [
    "flet",
    "requests",
    "beautifulsoup4",
    "adb-shell",
    "rsa",
]

[tool.flet]
product_name = "Auto TV"
icon = "assets/icon.png"

[tool.flet.flutter.dependencies]
wakelock_plus = "^1.2.8"

[tool.flet.android]
permissions = [
    "android.permission.WAKE_LOCK"
]
adaptive_icon_background = "#0f141c"
