name: Build Flet APK

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake git
          git config --global --add safe.directory "*"

      - name: Instalar Flet
        run: pip install flet

      - name: Gerar APK
        run: |
          flet build apk --yes --android-adaptive-icon-background "#111827"

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Auto-TV-APK
          path: build/apk/*.apk
